/*
 * Copyright (c) 2026 EdgeImpulse Inc.
 *
 * Generated by Edge Impulse and licensed under the applicable Edge Impulse
 * Terms of Service. Community and Professional Terms of Service
 * (https://edgeimpulse.com/legal/terms-of-service) or Enterprise Terms of
 * Service (https://edgeimpulse.com/legal/enterprise-terms-of-service),
 * according to your product plan subscription (the “License”).
 *
 * This software, documentation and other associated files (collectively referred
 * to as the “Software”) is a single SDK variation generated by the Edge Impulse
 * platform and requires an active paid Edge Impulse subscription to use this
 * Software for any purpose.
 *
 * You may NOT use this Software unless you have an active Edge Impulse subscription
 * that meets the eligibility requirements for the applicable License, subject to
 * your full and continued compliance with the terms and conditions of the License,
 * including without limitation any usage restrictions under the applicable License.
 *
 * If you do not have an active Edge Impulse product plan subscription, or if use
 * of this Software exceeds the usage limitations of your Edge Impulse product plan
 * subscription, you are not permitted to use this Software and must immediately
 * delete and erase all copies of this Software within your control or possession.
 * Edge Impulse reserves all rights and remedies available to enforce its rights.
 *
 * Unless required by applicable law or agreed to in writing, the Software is
 * distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
 * either express or implied. See the License for the specific language governing
 * permissions, disclaimers and limitations under the License.
 */

#ifndef _EI_CLASSIFIER_MODEL_VARIABLES_H_
#define _EI_CLASSIFIER_MODEL_VARIABLES_H_

/**
 * @file
 *  Auto-generated complete impulse definitions. The ei_impulse_handle_t should
 *  be passed to ei_run_classifier() function to use this specific impulse.
 *  This file should only be included in ei_run_classifier.h file.
 */

#include <stdint.h>
#include "model_metadata.h"
#include "tflite-model/tflite_learn_1074360_4_compiled.h"
#include "edge-impulse-sdk/classifier/ei_model_types.h"
#include "edge-impulse-sdk/classifier/inferencing_engines/engines.h"
#include "edge-impulse-sdk/classifier/postprocessing/ei_postprocessing_common.h"

const char* ei_classifier_inferencing_categories_1074360_1[] = { "fall", "non_fall" };

EI_CLASSIFIER_DSP_AXES_INDEX_TYPE ei_dsp_config_1074360_2_axes[] = { 0, 1, 2, 3, 4, 5 };
const uint32_t ei_dsp_config_1074360_2_axes_size = 6;
ei_dsp_config_spectral_analysis_t ei_dsp_config_1074360_2 = {
    2, // uint32_t blockId
    4, // int implementationVersion
    6, // int length of axes
    1.0f, // float scale-axes
    1, // int input-decimation-ratio
    "none", // select filter-type
    3.0f, // float filter-cutoff
    6, // int filter-order
    "FFT", // select analysis-type
    16, // int fft-length
    3, // int spectral-peaks-count
    0.1f, // float spectral-peaks-threshold
    "0.1, 0.5, 1.0, 2.0, 5.0", // string spectral-power-edges
    true, // boolean do-log
    true, // boolean do-fft-overlap
    1, // int wavelet-level
    "db4", // select wavelet
    false // boolean extra-low-freq
};

const float ei_dn_standard_scaler_mean_1074360_2[78] = { 0.14840322911009393, 0.03840654602626691, 1.622187872870347, 1.5069694372157116, 1.2088492322914504, -1.7389004291979142, -1.99508113665286, -2.2527769454314397, -2.5720866476311475, -2.880138440428906, -3.0572458557985924, -3.174568701636147, -3.1772762943763992, 0.13678416415791003, 0.1257957217371645, 1.6288263127837028, 1.5042755194511768, 1.1389186143359118, -1.795333202764694, -1.9981571320488394, -2.292520437553223, -2.6451387489088685, -2.9517954088546134, -3.1719275269959426, -3.2597932739032283, -3.264894350557714, 0.14194364702750653, 0.0851978543843772, 1.7823210121509996, 1.615256380289793, 1.5518445939933125, -1.8938804471619881, -2.096029965609715, -2.338200026191771, -2.712254044703661, -3.0065913918755345, -3.1517632742588586, -3.2388689574357628, -3.258839156982061, 25.83572660406699, 0.1344298615082595, 1.6013101990007468, 1.5077301959532339, 1.095617403962171, 2.7771001304185168, 2.502198058130169, 2.222487452855283, 1.7810082421134654, 1.4077730975491372, 1.208059262081578, 1.0950228062936582, 1.114521632184954, 25.825542284024728, 0.16225678059492712, 1.3864306500220884, 1.5925044083111994, 1.3440322566998597, 2.7662716000215024, 2.4971755374961604, 2.205106490832829, 1.8231233298916973, 1.486803247285, 1.273780916018311, 1.21315071251042, 1.2142879590832603, 24.6217952936485, 0.1246140634018072, 1.3449175140389393, 1.640241124944107, 1.5824496086727753, 2.6251633439489916, 2.236403671423653, 2.0200292766369516, 1.672969703285678, 1.3699718528927456, 1.1617670094443333, 1.0421157550519786, 1.0147997416505539 };
const float ei_dn_standard_scaler_scale_1074360_2[78] = { 4.49236430380154, 1.0244048198388669, 0.32135231780205686, 1.51454820391524, 0.5563869813307524, 0.6861740664890111, 0.7101564255258291, 0.7528869998681493, 0.7616566695412311, 0.7411080598351181, 0.7715498790963821, 0.8118546461454962, 0.80085611238115, 4.994030813167542, 0.9822909229078751, 0.2687184859241186, 1.582132782822049, 0.5419258353194644, 0.6997461890799582, 0.7095393805700271, 0.7201799579472756, 0.7560263844475048, 0.7637351928021437, 0.7585592817703363, 0.7933713324265156, 0.7801886848700218, 4.6119424268339415, 1.0382034444671586, 0.2788977721651539, 1.4990719769774528, 0.5333434150573223, 0.6660579143213763, 0.6614751414648541, 0.7159828231744806, 0.7180421750732546, 0.7602472106089944, 0.8011992055263311, 0.7960491984261943, 0.7809693090531539, 0.026968183167618866, 0.9621277614826826, 0.3385289132535038, 1.7427244165741345, 0.5909688788927818, 0.639019755249781, 0.6679708630262519, 0.7009345922072548, 0.7229327100102468, 0.7046208406794358, 0.6997576310052714, 0.7019971988915956, 0.7002776522016162, 0.030048540920592257, 0.9883498031090425, 0.3315559142783308, 1.7640871925117132, 0.5802958809799897, 0.6368108802826414, 0.6638134141235574, 0.6943578750616247, 0.6947974113030142, 0.6851718376186798, 0.6970513853421878, 0.6982549690643458, 0.6820752498822373, 0.02819076215775872, 1.0175692492499038, 0.32160692376833233, 1.5060333591007413, 0.5241852446416879, 0.6386968979785377, 0.6867259399949012, 0.7258343777461159, 0.7363967851977494, 0.704253189124613, 0.6828770023274118, 0.6771286770425308, 0.6659964515916107 };
const float ei_dn_standard_scaler_var_1074360_2[78] = { 0.04955073086156726, 0.9529207276030213, 9.683606352434683, 0.43594710643969004, 3.2303239763895917, 2.123886965918258, 1.9828595720944249, 1.7641698821813734, 1.7237786650776157, 1.8206938581239036, 1.6798557293392535, 1.5172021138793303, 1.559161171489828, 0.04009567829168733, 1.0363817059245715, 13.848569418110545, 0.3994975690889098, 3.4050248723116163, 2.042297078889969, 1.9863098259905603, 1.9280484262405224, 1.7495489409734453, 1.7144088243438445, 1.737884646651208, 1.5887186458655627, 1.6428605656419049, 0.04701454589729192, 0.9277587717049838, 12.85611976955268, 0.44499489479126614, 3.5154920904152727, 2.254114713365779, 2.2854564194898837, 1.9507193550571222, 1.9395460367267947, 1.7301761825550641, 1.5578261153145285, 1.578047898606143, 1.6395779379452131, 1374.980761099955, 1.0802754532057772, 8.725864523120691, 0.3292627249813953, 2.863325875426941, 2.4489021409615344, 2.2412224402011725, 2.0353777036261844, 1.9133933013857778, 2.014137111080153, 2.0422302911378623, 2.029220502296226, 2.0391983259796844, 1107.524195319028, 1.0237139934485437, 9.096753813706691, 0.32133638684695526, 2.9696209897599655, 2.4659203808324874, 2.2693838062229776, 2.074117086271863, 2.0714936992130055, 2.1301049028735903, 2.0581186621162257, 2.0510296091986, 2.14948994757522, 1258.306282617893, 0.9657663106281646, 9.668280015594613, 0.4408905766386953, 3.639405243488313, 2.451378576023409, 2.120474699383268, 1.8981255375500496, 1.8440650302890125, 2.0162405986869483, 2.1444455629066974, 2.1810096445528577, 2.254530782959108 };
ei_data_normalization_standard_scaler_config_t ei_data_normalization_standard_scaler_config_1074360_2 = {
    .mean_data = (float *)ei_dn_standard_scaler_mean_1074360_2,
    .mean_data_len = 78,
    .scale_data = (float *)ei_dn_standard_scaler_scale_1074360_2,
    .scale_data_len = 78,
    .var_data = (float *)ei_dn_standard_scaler_var_1074360_2,
    .var_data_len = 78
};
ei_data_normalization_t ei_data_normalization_config_1074360_2 = {
    (void *) &ei_data_normalization_standard_scaler_config_1074360_2, // config
    DATA_NORMALIZATION_METHOD_STANDARD_SCALER, // method
    nullptr, // context
    nullptr, // init func
    nullptr, // deinit func
    &data_normalization_standard_scaler // exec func
};

const uint8_t ei_dsp_blocks_1074360_1_size = 1;
ei_model_dsp_t ei_dsp_blocks_1074360_1[ei_dsp_blocks_1074360_1_size] = {
    { // DSP block 2
        2,
        78, // output size
        &extract_spectral_analysis_features, // DSP function pointer
        (void*)&ei_dsp_config_1074360_2, // pointer to config struct
        ei_dsp_config_1074360_2_axes, // array of offsets into the input stream, one for each axis
        ei_dsp_config_1074360_2_axes_size, // number of axes
        1, // version
        nullptr, // factory function
        &ei_data_normalization_config_1074360_2, // data normalization config
    }
};
const ei_config_tflite_eon_graph_t ei_config_graph_1074360_4 = {
    .implementation_version = 1,
    .model_init = &tflite_learn_1074360_4_init,
    .model_invoke = &tflite_learn_1074360_4_invoke,
    .model_reset = &tflite_learn_1074360_4_reset,
    .model_input = &tflite_learn_1074360_4_input,
    .model_output = &tflite_learn_1074360_4_output,
};

const uint8_t ei_output_tensors_indices_1074360_4[1] = { 0 };
const uint8_t ei_output_tensors_size_1074360_4 = 1;
ei_learning_block_config_tflite_graph_t ei_learning_block_config_1074360_4 = {
    .implementation_version = 1,
    .block_id = 4,
    .output_tensors_indices = ei_output_tensors_indices_1074360_4,
    .output_tensors_size = ei_output_tensors_size_1074360_4,
    .quantized = 1,
    .compiled = 1,
    .graph_config = (void*)&ei_config_graph_1074360_4,
    .dequantize_output = 0,
};

const uint8_t ei_learning_blocks_1074360_1_size = 1;
const uint32_t ei_learning_block_1074360_4_inputs[1] = { 2 };
const uint8_t ei_learning_block_1074360_4_inputs_size = 1;
const ei_learning_block_t ei_learning_blocks_1074360_1[ei_learning_blocks_1074360_1_size] = {
    {
        4,
        &run_nn_inference,
        (void*)&ei_learning_block_config_1074360_4,
        EI_CLASSIFIER_IMAGE_SCALING_NONE,
        ei_learning_block_1074360_4_inputs,
        ei_learning_block_1074360_4_inputs_size,
    },
};

ei_fill_result_classification_i8_config_t ei_fill_result_classification_i8_config_1074360_4 = {
    .zero_point = -128,
    .scale = 0.00390625
};

const size_t ei_postprocessing_blocks_1074360_1_size = 1;
const ei_postprocessing_block_t ei_postprocessing_blocks_1074360_1[ei_postprocessing_blocks_1074360_1_size] = {
    {
        .block_id = 4,
        .type = EI_CLASSIFIER_MODE_CLASSIFICATION,
        .init_fn = NULL,
        .deinit_fn = NULL,
        .postprocess_fn = &process_classification_i8,
        .display_fn = NULL,
        .config = (void*)&ei_fill_result_classification_i8_config_1074360_4,
        .input_block_id = 4
    },
};

const uint8_t freeform_outputs_1074360_1_size = 0;

uint32_t *freeform_outputs_1074360_1 = nullptr;

const ei_impulse_t impulse_1074360_1 = {
    .project_id = 1074360,
    .project_owner = "akuseru0509",
    .project_name = "akuseru0509-project-1",
    .impulse_id = 1,
    .impulse_name = "Impulse #1",
    .deploy_version = 1,

    .nn_input_frame_size = 78,
    .raw_sample_count = 75,
    .raw_samples_per_frame = 6,
    .dsp_input_frame_size = 75 * 6,
    .input_width = 0,
    .input_height = 0,
    .input_frames = 0,
    .interval_ms = 20,
    .frequency = 50,

    .dsp_blocks_size = ei_dsp_blocks_1074360_1_size,
    .dsp_blocks = ei_dsp_blocks_1074360_1,

    .learning_blocks_size = ei_learning_blocks_1074360_1_size,
    .learning_blocks = ei_learning_blocks_1074360_1,

    .postprocessing_blocks_size = ei_postprocessing_blocks_1074360_1_size,
    .postprocessing_blocks = ei_postprocessing_blocks_1074360_1,

    .output_tensors_size = 1,

    .inferencing_engine = EI_CLASSIFIER_TFLITE,

    .sensor = EI_CLASSIFIER_SENSOR_FUSION,
    .fusion_string = "accX + accY + accZ + gyrX + gyrY + gyrZ",
    .slice_size = (75/4),
    .slices_per_model_window = 4,

    .has_anomaly = EI_ANOMALY_TYPE_UNKNOWN,
    .label_count = 2,
    .categories = ei_classifier_inferencing_categories_1074360_1,
    .results_type = EI_CLASSIFIER_TYPE_CLASSIFICATION,
    .freeform_outputs_size = freeform_outputs_1074360_1_size,
    .freeform_outputs = freeform_outputs_1074360_1
};

ei_impulse_handle_t impulse_handle_1074360_1 = ei_impulse_handle_t( &impulse_1074360_1 );

ei_impulse_handle_t& ei_default_impulse = impulse_handle_1074360_1;
constexpr auto& ei_classifier_inferencing_categories = ei_classifier_inferencing_categories_1074360_1;
const auto ei_dsp_blocks_size = ei_dsp_blocks_1074360_1_size;
ei_model_dsp_t *ei_dsp_blocks = ei_dsp_blocks_1074360_1;
#endif // _EI_CLASSIFIER_MODEL_VARIABLES_H_
